import { Raleway } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
